#!/usr/bin/env python3
"""Regenerate the PY_* fixtures embedded in rust-cli/tests/synthesis_parity.rs.

Run from the repo root with the project venv:

    .venv/bin/python tools/gen_synthesis_fixture.py

The Rust port is compared byte-for-byte against these strings, which come from
actually EXECUTING koiosbase/compile/synthesis.py. Expected values derived by
reading the source are worthless — they inherit your misreading.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from koiosbase.compile.synthesis import render_synthesis  # noqa: E402

OUT = REPO / "rust-cli" / "tests" / "synthesis_parity.rs"
BEGIN = "// --- BEGIN PYTHON-GENERATED FIXTURES ---"
END = "// --- END PYTHON-GENERATED FIXTURES ---"


def cases() -> list[tuple[str, str]]:
    """(CONST_SUFFIX, python output) — add a case here, rerun, commit both."""
    out = []

    def case(name, *args, **kw):
        out.append((name.upper(), render_synthesis(*args, **kw)))

    # More facts/entities than the caps, so both truncation points are asserted.
    case(
        "typical",
        "finance",
        ["acme", "beta", "gamma"],
        [
            ("营收 32 亿", "r.md#财务分析/1"),
            ("负债 18 亿", "r.md#负债分析/2"),
            ("现金流为正", "r.md#现金流/3"),
            ("毛利率 41%", "r.md#财务分析/4"),
            ("研发投入 3 亿", "r.md#研发/5"),
            ("海外收入占比 22%", "r.md#营收结构/6"),
            ("存货周转 5.2 次", "r.md#营运/7"),
            ("应收账款 9 亿", "r.md#营运/8"),
            ("资本开支 4 亿", "r.md#现金流/9"),
            ("员工 1200 人", "r.md#人力/10"),
        ],
        "2026-10-08",
    )
    # No inputs at all -> both (暂无) fallbacks and an empty sources list.
    case("empty", "empty", [], [], "2026-10-08")
    case("single", "single", ["only"], [("唯一事实", "d.md#s/1")], "2026-10-08")
    case("stale", "stale", ["acme"], [("营收 32 亿", "r.md#s/1")], "2026-10-08", True)
    # CJK + full-width punctuation in title, ids and entity names.
    case(
        "cjk",
        "2024 年报（合并）",
        ["ＡＣＭＥ", "财务/风控"],
        [("（含税）营收：32 亿元。", "年报.md#财务分析 > 营收/1")],
        "2026-01-02",
    )
    return out


def main() -> int:
    text = OUT.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"{OUT}: missing {BEGIN} / {END} markers")

    parts = [
        BEGIN,
        "// Generated by tools/gen_synthesis_fixture.py — do not hand-edit.",
        "//",
        "// The Rust port is diffed against these byte for byte. Every string",
        "// below is REAL output from koiosbase/compile/synthesis.py, not an",
        "// expectation written by reading the Python and guessing the result.",
        "",
    ]
    for name, body in cases():
        # r#"..."# swallows every byte in these fixtures; fail loudly if that
        # ever stops being true rather than emitting a broken literal.
        if '"#' in body or "\\" in body:
            sys.exit(f"fixture {name} needs an escaped raw literal")
        parts.append(f"pub(crate) const PY_{name}: &str = r#\"{body}\"#;\n")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    OUT.write_text(head + "\n".join(parts) + END + tail, encoding="utf-8")
    print(f"regenerated {len(cases())} fixtures in {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
