//! §8.3 lazy synthesis update — ported from koiosbase/compile/synthesis.py.
//!
//! The `PY_*` constants below are REAL output from the Python implementation,
//! regenerated by `tools/gen_synthesis_fixture.py`. Expected values written by
//! reading the source inherit whatever you misread; these do not.

use std::fs;
use std::path::PathBuf;

use koios::compile::{
    mark_syntheses_stale, needs_recompile, recompile_synthesis, render_synthesis, stamp_now,
};
use koios::connect;

// --- BEGIN PYTHON-GENERATED FIXTURES ---
// Generated by tools/gen_synthesis_fixture.py — do not hand-edit.
//
// The Rust port is diffed against these byte for byte. Every string
// below is REAL output from koiosbase/compile/synthesis.py, not an
// expectation written by reading the Python and guessing the result.

pub(crate) const PY_TYPICAL: &str = r#"---
type: synthesis
confidence: draft
generated: true
last_compiled: 2026-10-08
stale: false
sources: [raw/r.md#财务分析/1, raw/r.md#负债分析/2, raw/r.md#现金流/3]
---

# finance

## 综合结论
- 营收 32 亿 [[raw/r.md#财务分析/1]]
- 负债 18 亿 [[raw/r.md#负债分析/2]]
- 现金流为正 [[raw/r.md#现金流/3]]
- 毛利率 41% [[raw/r.md#财务分析/4]]
- 研发投入 3 亿 [[raw/r.md#研发/5]]
- 海外收入占比 22% [[raw/r.md#营收结构/6]]
- 存货周转 5.2 次 [[raw/r.md#营运/7]]
- 应收账款 9 亿 [[raw/r.md#营运/8]]

## 覆盖实体
- [[entities/acme]]
- [[entities/beta]]
- [[entities/gamma]]
"#;

pub(crate) const PY_EMPTY: &str = r#"---
type: synthesis
confidence: draft
generated: true
last_compiled: 2026-10-08
stale: false
sources: []
---

# empty

## 综合结论
- (暂无)

## 覆盖实体
- (暂无)
"#;

pub(crate) const PY_SINGLE: &str = r#"---
type: synthesis
confidence: draft
generated: true
last_compiled: 2026-10-08
stale: false
sources: [raw/d.md#s/1]
---

# single

## 综合结论
- 唯一事实 [[raw/d.md#s/1]]

## 覆盖实体
- [[entities/only]]
"#;

pub(crate) const PY_STALE: &str = r#"---
type: synthesis
confidence: draft
generated: true
last_compiled: 2026-10-08
stale: true
sources: [raw/r.md#s/1]
---

# stale

## 综合结论
- 营收 32 亿 [[raw/r.md#s/1]]

## 覆盖实体
- [[entities/acme]]
"#;

pub(crate) const PY_CJK: &str = r#"---
type: synthesis
confidence: draft
generated: true
last_compiled: 2026-01-02
stale: false
sources: [raw/年报.md#财务分析 > 营收/1]
---

# 2024 年报（合并）

## 综合结论
- （含税）营收：32 亿元。 [[raw/年报.md#财务分析 > 营收/1]]

## 覆盖实体
- [[entities/ＡＣＭＥ]]
- [[entities/财务/风控]]
"#;
// --- END PYTHON-GENERATED FIXTURES ---

struct TmpVault {
    p: PathBuf,
}

impl Drop for TmpVault {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.p);
    }
}

fn vault(name: &str) -> TmpVault {
    let p = std::env::temp_dir().join(format!("koios-synth-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&p);
    koios::init_vault(&p).unwrap();
    TmpVault { p }
}

/// The fixture PY_TYPICAL was generated from — one source of truth so the render
/// test can never drift from the strings actually compared against Python.
fn typical_facts() -> Vec<(String, String)> {
    [
        ("营收 32 亿", "r.md#财务分析/1"),
        ("负债 18 亿", "r.md#负债分析/2"),
        ("现金流为正", "r.md#现金流/3"),
        ("毛利率 41%", "r.md#财务分析/4"),
        ("研发投入 3 亿", "r.md#研发/5"),
        ("海外收入占比 22%", "r.md#营收结构/6"),
        ("存货周转 5.2 次", "r.md#营运/7"),
        ("应收账款 9 亿", "r.md#营运/8"),
        ("资本开支 4 亿", "r.md#现金流/9"),
        ("员工 1200 人", "r.md#人力/10"),
    ]
    .iter()
    .map(|(t, b)| (t.to_string(), b.to_string()))
    .collect()
}

fn s(v: &[&str]) -> Vec<String> {
    v.iter().map(|x| x.to_string()).collect()
}

fn touch(v: &std::path::Path, name: &str) {
    let d = v.join("wiki").join("synthesis");
    fs::create_dir_all(&d).unwrap();
    fs::write(d.join(name), "# outdated\n").unwrap();
}

// ------------------------------------------------------------- render parity --

/// render_synthesis must be byte-identical to Python, caps included: facts are
/// sliced to 8 for the body, 3 for `sources`, entities to 10.
#[test]
fn render_matches_python_typical() {
    let got = render_synthesis(
        "finance",
        &s(&["acme", "beta", "gamma"]),
        &typical_facts(),
        "2026-10-08",
        false,
    );
    assert_eq!(got, PY_TYPICAL, "full page must match Python byte for byte");
}

#[test]
fn render_matches_python_empty() {
    let got = render_synthesis("empty", &[], &[], "2026-10-08", false);
    assert_eq!(got, PY_EMPTY, "empty inputs must hit both (暂无) fallbacks");
}

#[test]
fn render_matches_python_single() {
    let got = render_synthesis(
        "single",
        &s(&["only"]),
        &[("唯一事实".to_string(), "d.md#s/1".to_string())],
        "2026-10-08",
        false,
    );
    assert_eq!(got, PY_SINGLE);
}

#[test]
fn render_matches_python_stale() {
    let got = render_synthesis(
        "stale",
        &s(&["acme"]),
        &[("营收 32 亿".to_string(), "r.md#s/1".to_string())],
        "2026-10-08",
        true,
    );
    assert_eq!(got, PY_STALE, "stale must lower to 'true', not 'True'");
}

#[test]
fn render_matches_python_cjk() {
    let got = render_synthesis(
        "2024 年报（合并）",
        &s(&["ＡＣＭＥ", "财务/风控"]),
        &[(
            "（含税）营收：32 亿元。".to_string(),
            "年报.md#财务分析 > 营收/1".to_string(),
        )],
        "2026-01-02",
        false,
    );
    assert_eq!(got, PY_CJK, "CJK + punctuation title must survive intact");
}

/// The caps only bite above the threshold — verify the 9th fact and 11th entity
/// are dropped while exactly 8/10 survive. An off-by-one here is invisible to
/// eyeballing a rendered page.
#[test]
fn render_caps_facts_at_eight_and_entities_at_ten() {
    let page = render_synthesis(
        "caps",
        &(1..=12).map(|i| format!("e{i}")).collect::<Vec<_>>(),
        &typical_facts(),
        "2026-10-08",
        false,
    );
    assert!(page.contains("- 应收账款 9 亿"), "8th fact must be present");
    assert!(!page.contains("资本开支 4 亿"), "9th fact must be dropped");
    assert!(page.contains("- [[entities/e10]]"), "10th entity kept");
    assert!(!page.contains("[[entities/e11]]"), "11th entity dropped");
    // `sources` caps at 3 ids even though the body lists 8 — check the LINE,
    // not the whole page: `r.md#财务分析/4` legitimately appears further down.
    let src = page
        .lines()
        .find(|l| l.starts_with("sources:"))
        .expect("sources line");
    assert_eq!(
        src,
        "sources: [raw/r.md#财务分析/1, raw/r.md#负债分析/2, raw/r.md#现金流/3]"
    );
}

#[test]
fn stamp_now_is_utc_iso_date() {
    let d = stamp_now();
    assert_eq!(d.len(), 10, "date stamp must be YYYY-MM-DD; got {d}");
    assert_eq!(&d[4..5], "-");
    assert_eq!(&d[7..8], "-");
    assert!(d.chars().all(|c| c.is_ascii_digit() || c == '-'));
}

// ----------------------------------------------------------- needs_recompile --

#[test]
fn needs_recompile_true_when_page_missing() {
    let v = vault("missing");
    let conn = connect(&v.p).unwrap();
    assert!(
        needs_recompile(&conn, &v.p, "finance"),
        "a topic with no page must be compiled (Python: `not target.exists()`)"
    );
}

#[test]
fn needs_recompile_false_for_fresh_page() {
    let v = vault("fresh");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    assert!(!needs_recompile(&conn, &v.p, "finance"));
}

#[test]
fn needs_recompile_true_when_page_stale() {
    let v = vault("staleflag");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    koios::state::mark_stale(&conn, "wiki/synthesis/finance.md", "src changed").unwrap();
    assert!(needs_recompile(&conn, &v.p, "finance"));
}

// ------------------------------------------------------- mark_syntheses_stale --

#[test]
fn mark_all_when_topics_is_none() {
    let v = vault("all");
    touch(&v.p, "a.md");
    touch(&v.p, "b.md");
    let conn = connect(&v.p).unwrap();
    let touched = mark_syntheses_stale(&conn, &v.p, None).unwrap();
    // sorted by filename, same as Python's sorted(glob(...))
    assert_eq!(touched, vec!["wiki/synthesis/a.md", "wiki/synthesis/b.md"]);
    assert!(koios::state::is_stale(&conn, "wiki/synthesis/a.md"));
    assert!(koios::state::is_stale(&conn, "wiki/synthesis/b.md"));
}

#[test]
fn mark_only_named_topics() {
    let v = vault("filtered");
    touch(&v.p, "finance.md");
    touch(&v.p, "risk.md");
    touch(&v.p, "ops.md");
    let conn = connect(&v.p).unwrap();
    let touched = mark_syntheses_stale(&conn, &v.p, Some(&["finance".to_string()])).unwrap();
    assert_eq!(touched, vec!["wiki/synthesis/finance.md"]);
    assert!(koios::state::is_stale(&conn, "wiki/synthesis/finance.md"));
    // the whole point of `topics`: these must NOT have been flagged
    assert!(
        !koios::state::is_stale(&conn, "wiki/synthesis/risk.md"),
        "topics must narrow the blast radius"
    );
    assert!(!koios::state::is_stale(&conn, "wiki/synthesis/ops.md"));
}

#[test]
fn mark_syntheses_stale_no_dir_is_empty() {
    let v = vault("nodir");
    let conn = connect(&v.p).unwrap();
    let touched = mark_syntheses_stale(&conn, &v.p, None).unwrap();
    assert!(
        touched.is_empty(),
        "missing synthesis dir -> nothing touched"
    );
}

#[test]
fn topics_are_trimmed_and_empty_entries_dropped() {
    let v = vault("trim");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    let touched = mark_syntheses_stale(
        &conn,
        &v.p,
        Some(&["  finance  ".to_string(), "  ".to_string()]),
    )
    .unwrap();
    assert_eq!(touched, vec!["wiki/synthesis/finance.md"]);
}

#[test]
fn empty_topics_list_marks_nothing() {
    // Python: `wanted = {t.strip() for t in topics if t and t.strip()}` -> {} —
    // an empty SET, not None, so `p.stem not in wanted` filters everything out.
    let v = vault("emptytopics");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    let touched = mark_syntheses_stale(&conn, &v.p, Some(&[])).unwrap();
    assert!(
        touched.is_empty(),
        "Some([]) matches nothing, unlike None which matches all"
    );
    assert!(!koios::state::is_stale(&conn, "wiki/synthesis/finance.md"));
}

// --------------------------------------------------------- recompile clears --

#[test]
fn recompile_writes_page_and_clears_stale() {
    let v = vault("recompile");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    mark_syntheses_stale(&conn, &v.p, None).unwrap();
    assert!(needs_recompile(&conn, &v.p, "finance"));

    let facts = [("营收 32 亿".to_string(), "r.md#财务分析/1".to_string())];
    let target = recompile_synthesis(&conn, &v.p, "finance", &s(&["acme"]), &facts).unwrap();
    assert_eq!(
        target,
        v.p.join("wiki").join("synthesis").join("finance.md")
    );
    assert!(
        !needs_recompile(&conn, &v.p, "finance"),
        "recompile must clear the stale flag or lazy update never terminates"
    );

    let text = fs::read_to_string(&target).unwrap();
    assert!(
        text.contains("[[raw/r.md#财务分析/1]]"),
        "must cite raw (P6)"
    );
    assert!(text.contains("[[entities/acme]]"));
    assert!(text.contains("stale: false"));
    // identical to what Python's recompile writes for the same inputs
    assert_eq!(
        text,
        render_synthesis("finance", &s(&["acme"]), &facts, &stamp_now(), false)
    );
}

#[test]
fn recompile_records_recompiled_reason_and_active_state() {
    let v = vault("rowstate");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    mark_syntheses_stale(&conn, &v.p, None).unwrap();
    recompile_synthesis(&conn, &v.p, "finance", &[], &[]).unwrap();
    // Normalised key (see `state::normalize_page_key`): the cascade and the
    // reader must agree on what a page is called, or §8.3 resolves nothing.
    let (stale, state, reason): (i64, String, String) = conn
        .query_row(
            "SELECT stale,state,reason FROM page_state WHERE page_path=?",
            rusqlite::params![koios::state::normalize_page_key(
                "wiki/synthesis/finance.md"
            )],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
        )
        .unwrap();
    assert_eq!(stale, 0);
    // Recompiling clears staleness; it does not overwrite a human's lifecycle
    // state. This page was never disputed, so it reads active.
    assert_eq!(state, "active");
    assert_eq!(reason, "recompiled");
}

#[test]
fn recompile_preserves_a_disputed_state() {
    let v = vault("disputed");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();
    koios::state::set_page_state(
        &conn,
        "wiki/synthesis/finance.md",
        0,
        "disputed",
        "human flagged",
    )
    .unwrap();
    mark_syntheses_stale(&conn, &v.p, None).unwrap();
    recompile_synthesis(&conn, &v.p, "finance", &[], &[]).unwrap();
    let all: Vec<(String, i64, String)> = conn
        .prepare("select page_path,stale,state from page_state")
        .unwrap()
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))
        .unwrap()
        .filter_map(Result::ok)
        .collect();
    let (stale, state): (i64, String) = conn
        .query_row(
            "SELECT stale,state FROM page_state WHERE page_path=?",
            rusqlite::params![koios::state::normalize_page_key(
                "wiki/synthesis/finance.md"
            )],
            |r| Ok((r.get(0)?, r.get(1)?)),
        )
        .unwrap();
    assert_eq!(stale, 0, "recompile clears the staleness flag; rows={all:?}");
    assert_eq!(
        state, "disputed",
        "recompile must not silently clear a human's lifecycle state; rows={all:?}"
    );
}

#[test]
fn recompile_creates_page_when_absent() {
    let v = vault("create");
    let conn = connect(&v.p).unwrap();
    let target = recompile_synthesis(&conn, &v.p, "newtopic", &[], &[]).unwrap();
    assert!(target.exists(), "recompile must create page and dir");
    assert!(!needs_recompile(&conn, &v.p, "newtopic"));
    assert!(fs::read_to_string(&target).unwrap().contains("- (暂无)"));
}

/// Port of tests/test_state_cascade.py::test_lazy_synthesis, end to end.
#[test]
fn lazy_synthesis_lifecycle() {
    let v = vault("lifecycle");
    touch(&v.p, "finance.md");
    let conn = connect(&v.p).unwrap();

    assert!(!needs_recompile(&conn, &v.p, "finance"));
    mark_syntheses_stale(&conn, &v.p, None).unwrap();
    assert!(
        needs_recompile(&conn, &v.p, "finance"),
        "lazy update not flagged"
    );

    recompile_synthesis(
        &conn,
        &v.p,
        "finance",
        &s(&["acme"]),
        &[("营收 32 亿".to_string(), "r.md#财务分析/1".to_string())],
    )
    .unwrap();
    assert!(
        !needs_recompile(&conn, &v.p, "finance"),
        "stale flag not cleared"
    );
    let text = fs::read_to_string(v.p.join("wiki").join("synthesis").join("finance.md")).unwrap();
    assert!(text.contains("[[raw/"));
}
